name: 'Check Application - CI'
on:
  push:
    branches: [main]
  pull_request:
    branches: [dev]

jobs:
  test_backend_core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/core
    steps:
      - name: Install dependencies
        uses: ./.github/actions/setup-node
      - name: Run tests
        run: pnpm test
